In [328]:
import json
from pathlib import Path
from datetime import date
import pandas as pd 
import os

In [329]:
paris_summer = pd.read_csv("./raw/olympics/olympics_paris2024.csv",encoding="utf-8")
winter_summer_games = pd.read_csv("./raw/olympics/olympics_history.csv",encoding="utf-8")

In [330]:
paris_summer

,country_code,country,country_long,Gold Medal,Silver Medal,Bronze Medal,Total
0,USA,United States,United States of America,40,44,42,126
1,CHN,China,People's Republic of China,40,27,24,91
2,JPN,Japan,Japan,20,12,13,45
3,AUS,Australia,Australia,18,19,16,53
4,FRA,France,France,16,26,22,64
...,...,...,...,...,...,...,...
87,PER,Peru,Peru,0,0,1,1
88,QAT,Qatar,Qatar,0,0,1,1
89,SGP,Singapore,Singapore,0,0,1,1
90,SVK,Slovakia,Slovakia,0,0,1,1
91,ZAM,Zambia,Zambia,0,0,1,1

In [331]:
winter_summer_games

,year,edition,edition_id,country,country_noc,gold,silver,bronze,total
0,1896,1896 Summer Olympics,1,Greece,GRE,10,18,19,47
1,1900,1900 Summer Olympics,2,France,FRA,31,41,40,112
2,1900,1900 Summer Olympics,2,United States,USA,20,13,15,48
3,1904,1904 Summer Olympics,3,United States,USA,80,85,83,248
4,1908,1908 Summer Olympics,5,Great Britain,GBR,56,51,39,146
...,...,...,...,...,...,...,...,...,...
1802,2008,2008 Summer Olympics,53,Australia,AUS,14,15,17,46
1803,2008,2008 Summer Olympics,53,Cuba,CUB,3,10,17,30
1804,2012,2012 Summer Olympics,54,Japan,JPN,7,14,17,38
1805,2016,2016 Summer Olympics,59,Great Britain,GBR,27,23,17,67
1806,2020,2020 Summer Olympics,61,Japan,JPN,27,14,17,58

In [332]:
paris_summer_processed = (
    paris_summer
    .rename(columns={
    "country_code": "country_noc",
    "Gold Medal": "gold",
    "Silver Medal": "silver",
    "Bronze Medal": "bronze",
    "Total": "total"
    })
)

In [333]:
paris_summer_processed

,country_noc,country,country_long,gold,silver,bronze,total
0,USA,United States,United States of America,40,44,42,126
1,CHN,China,People's Republic of China,40,27,24,91
2,JPN,Japan,Japan,20,12,13,45
3,AUS,Australia,Australia,18,19,16,53
4,FRA,France,France,16,26,22,64
...,...,...,...,...,...,...,...
87,PER,Peru,Peru,0,0,1,1
88,QAT,Qatar,Qatar,0,0,1,1
89,SGP,Singapore,Singapore,0,0,1,1
90,SVK,Slovakia,Slovakia,0,0,1,1
91,ZAM,Zambia,Zambia,0,0,1,1

In [334]:
# paris_summer_processed = paris_summer_processed.groupby("country")[["gold","silver","bronze","total"]].sum()

In [335]:
# paris_summer_processed

In [336]:
# paris_summer_processed.reset_index(inplace=True)

In [337]:
# paris_summer_processed

In [338]:
# Separar por jogos de verão/inverno
summer = winter_summer_games[winter_summer_games["edition"].str.contains("Summer")]
winter = winter_summer_games[winter_summer_games["edition"].str.contains("Winter")]

summer = pd.concat([summer, paris_summer_processed])

# summer_medals = summer.groupby("country")["total"].sum()
# winter_medals = winter.groupby("country")["total"].sum()

In [339]:
summer

,year,edition,edition_id,country,country_noc,gold,silver,bronze,total,country_long
0,1896.0,1896 Summer Olympics,1.0,Greece,GRE,10,18,19,47,NaN
1,1900.0,1900 Summer Olympics,2.0,France,FRA,31,41,40,112,NaN
2,1900.0,1900 Summer Olympics,2.0,United States,USA,20,13,15,48,NaN
3,1904.0,1904 Summer Olympics,3.0,United States,USA,80,85,83,248,NaN
4,1908.0,1908 Summer Olympics,5.0,Great Britain,GBR,56,51,39,146,NaN
...,...,...,...,...,...,...,...,...,...,...
87,NaN,NaN,NaN,Peru,PER,0,0,1,1,Peru
88,NaN,NaN,NaN,Qatar,QAT,0,0,1,1,Qatar
89,NaN,NaN,NaN,Singapore,SGP,0,0,1,1,Singapore
90,NaN,NaN,NaN,Slovakia,SVK,0,0,1,1,Slovakia
91,NaN,NaN,NaN,Zambia,ZAM,0,0,1,1,Zambia

In [340]:
winter

,year,edition,edition_id,country,country_noc,gold,silver,bronze,total
101,1924,1924 Winter Olympics,29,Canada,CAN,1,0,0,1
102,1924,1924 Winter Olympics,29,Sweden,SWE,1,1,0,2
103,1924,1924 Winter Olympics,29,Mixed team,MIX,1,0,0,1
104,1924,1924 Winter Olympics,29,Austria,AUT,2,1,0,3
114,1928,1928 Winter Olympics,30,France,FRA,1,0,0,1
...,...,...,...,...,...,...,...,...,...
1729,2018,2018 Winter Olympics,60,Norway,NOR,14,14,11,39
1765,2010,2010 Winter Olympics,57,United States,USA,9,15,13,37
1768,2022,2022 Winter Olympics,62,Norway,NOR,16,8,13,37
1778,2022,2022 Winter Olympics,62,ROC,ROC,6,12,14,32
1779,2022,2022 Winter Olympics,62,Canada,CAN,4,8,14,26

In [341]:
# summer_medals = (
#     summer.groupby("country")[["gold","silver","bronze","total"]]
#     .sum()
#     .sort_values("total", ascending=False)
# )

# winter_medals = (
#     winter.groupby("country")[["gold","silver","bronze","total"]]
#     .sum()
#     .sort_values("total", ascending=False)
# )

# total_medals = (
#     winter_summer_games.groupby("country")[["gold","silver","bronze","total"]]
#     .sum()
#     .sort_values("total", ascending=False)
# )

In [342]:
bronze_medals = pd.concat([summer,winter])

In [343]:
bronze_medals

,year,edition,edition_id,country,country_noc,gold,silver,bronze,total,country_long
0,1896.0,1896 Summer Olympics,1.0,Greece,GRE,10,18,19,47,NaN
1,1900.0,1900 Summer Olympics,2.0,France,FRA,31,41,40,112,NaN
2,1900.0,1900 Summer Olympics,2.0,United States,USA,20,13,15,48,NaN
3,1904.0,1904 Summer Olympics,3.0,United States,USA,80,85,83,248,NaN
4,1908.0,1908 Summer Olympics,5.0,Great Britain,GBR,56,51,39,146,NaN
...,...,...,...,...,...,...,...,...,...,...
1729,2018.0,2018 Winter Olympics,60.0,Norway,NOR,14,14,11,39,NaN
1765,2010.0,2010 Winter Olympics,57.0,United States,USA,9,15,13,37,NaN
1768,2022.0,2022 Winter Olympics,62.0,Norway,NOR,16,8,13,37,NaN
1778,2022.0,2022 Winter Olympics,62.0,ROC,ROC,6,12,14,32,NaN
1779,2022.0,2022 Winter Olympics,62.0,Canada,CAN,4,8,14,26,NaN

In [370]:
len(bronze_medals)

1874

### Criação dos metadados para as medalhas

In [371]:
def criacao_metadados(path:str, data:list):
    with open(path,"w",encoding="UTF-8") as f:
        json.dump(data,f,ensure_ascii=False,indent=4)

In [372]:
metadatas_medalhas_olympics_json = [
    {
        "arquivo": "medals_olympics.csv",
        "descricao": "Dados das medalhas conquistadas pelos países nas respectivas edições dos Jogos Olímpicos",
        "formato": "csv",
        "delimitador": ",",
        "codificacao": "latin1",
        "quantidade_linhas": "1874",
        "dataset": "olympic_medals",
        "colunas": [
            {
                "nome": "year",
                "tipo_dado": "float64",
                "descricao": "Ano da edição dos Jogos Olímpicos"
            },
            {
                "nome": "edition",
                "tipo_dado": "string",
                "descricao": "Nome da edição dos Jogos Olímpicos (ex: Rio 2016)"
            },
            {
                "nome": "edition_id",
                "tipo_dado": "float64",
                "descricao": "Identificador único da edição dos Jogos Olímpicos"
            },
            {
                "nome": "country",
                "tipo_dado": "string",
                "descricao": "Nome do país (formato curto)"
            },
            {
                "nome": "country_noc",
                "tipo_dado": "string",
                "descricao": "Código do Comitê Olímpico Nacional (ex: BRA, USA)"
            },
            {
                "nome": "gold",
                "tipo_dado": "int64",
                "descricao": "Quantidade de medalhas de ouro conquistadas pelo país"
            },
            {
                "nome": "silver",
                "tipo_dado": "int64",
                "descricao": "Quantidade de medalhas de prata conquistadas pelo país"
            },
            {
                "nome": "bronze",
                "tipo_dado": "int64",
                "descricao": "Quantidade de medalhas de bronze conquistadas pelo país"
            },
            {
                "nome": "total",
                "tipo_dado": "int64",
                "descricao": "Quantidade total de medalhas (ouro + prata + bronze)"
            },
            {
                "nome": "country_long",
                "tipo_dado": "string",
                "descricao": "Nome completo do país (formato estendido)"
            }
        ]
    }
]

In [376]:
caminho_metadata_bronze = Path("./bronze/")
caminho_arquivo = caminho_metadata_bronze / "medals_olympics.json"

criacao_metadados(caminho_arquivo,metadatas_medalhas_olympics_json)

In [344]:
path = "./bronze/medals_olympics.csv"
if os.path.exists(path):
    pass
else:
    bronze_medals.to_csv(path)

### Atletas por sexo

In [345]:
atletas_olimpiadas = pd.read_csv("./raw/athletes/athletes_olympics.csv")
atletas_paris = pd.read_csv("./raw/athletes/athletes_paris.csv")

In [346]:
atletas_olimpiadas

,athlete_id,name,sex,birth_date,birth_year,height,weight,country,country_noc,description,special_notes
0,2303707,A. Sansores,Male,NaN,NaN,NaN,NaN,Cuba,CUB,NaN,NaN
1,2303703,Álvaro Ledón,Male,NaN,NaN,NaN,NaN,Cuba,CUB,NaN,NaN
2,921722,Abelardo Cuevas,Male,NaN,NaN,NaN,NaN,Cuba,CUB,"Abelardo Cuevas was a Cuban oboist, hornist, s...",NaN
3,2303702,V. Fernández,Male,NaN,NaN,NaN,NaN,Cuba,CUB,NaN,NaN
4,2303738,A. F. Ruiz,Male,NaN,NaN,NaN,NaN,Cuba,CUB,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
155856,141672,Quan Hongchan,Female,2007-03-28,2007.0,NaN,NaN,People's Republic of China,CHN,NaN,NaN
155857,144431,Kokona Hiraki,Female,2008-08-26,2008.0,NaN,NaN,Japan,JPN,NaN,NaN
155858,141168,Rayssa Leal,Female,2008-01-04,2008.0,147.0,35.0,Brazil,BRA,NaN,NaN
155859,143068,Sky Brown,Female,2008-07-07,2008.0,NaN,NaN,Great Britain,GBR,NaN,NaN
155860,146782,Hend Zaza,Female,2009-01-01,2009.0,NaN,NaN,Syrian Arab Republic,SYR,NaN,NaN

In [347]:
atletas_paris

,code,current,name,name_short,name_tv,gender,function,country_code,country,country_long,...,family,lang,coach,reason,hero,influence,philosophy,sporting_relatives,ritual,other_sports
0,1532872,True,ALEKSANYAN Artur,ALEKSANYAN A,Artur ALEKSANYAN,Male,Athlete,ARM,Armenia,Armenia,...,"Father, Gevorg Aleksanyan","Armenian, English, Russian","Gevorg Aleksanyan (ARM), father",He followed his father and his uncle into the ...,"Footballer Zinedine Zidane (FRA), World Cup wi...","His father, Gevorg Aleksanyan","""Wrestling is my life."" (mediamax.am. 18 May 2...",NaN,NaN,NaN
1,1532873,True,AMOYAN Malkhas,AMOYAN M,Malkhas AMOYAN,Male,Athlete,ARM,Armenia,Armenia,...,NaN,Armenian,NaN,NaN,NaN,NaN,"""To become a good athlete, you first have to b...","Uncle, Roman Amoyan (wrestling), 2008 Olympic ...",NaN,NaN
2,1532874,True,GALSTYAN Slavik,GALSTYAN S,Slavik GALSTYAN,Male,Athlete,ARM,Armenia,Armenia,...,NaN,Armenian,Personal: Martin Alekhanyan (ARM).<br>National...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1532944,True,HARUTYUNYAN Arsen,HARUTYUNYAN A,Arsen HARUTYUNYAN,Male,Athlete,ARM,Armenia,Armenia,...,"Wife, Diana (married October 2022). Daughter, ...",Armenian,National: Habetnak Kurghinyan,While doing karate he noticed wrestlers traini...,"Wrestler Armen Nazaryan (ARM, BUL), two-time O...",NaN,"“Nothing is impossible, set goals in front of ...",NaN,NaN,NaN
4,1532945,True,TEVANYAN Vazgen,TEVANYAN V,Vazgen TEVANYAN,Male,Athlete,ARM,Armenia,Armenia,...,"Wife, Sona (married November 2023)","Armenian, Russian",National: Habetnak Kurghinyan (ARM),“My family did not like wrestling very much. A...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11108,4986655,True,ADA ETO Sefora,ADA ETO S,Sefora ADA ETO,Female,Athlete,GEQ,Equatorial Guinea,Equatorial Guinea,...,NaN,Spanish,Personal: Feliciano Javier y Mananses Mba Micha,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11109,9460001,True,LIUZZI Emanuela,LIUZZI E,Emanuela LIUZZI,Female,Athlete,ITA,Italy,Italy,...,NaN,Italian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11110,1972077,False,BOERS Isayah,NaN,NaN,Male,Athlete,NED,Netherlands,Netherlands,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11111,1899865,False,STAUT Kevin,NaN,NaN,Male,Athlete,FRA,France,France,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11112,1924402,False,CARVELL Charlie,NaN,NaN,Male,Athlete,GBR,Great Britain,Great Britain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [348]:
atletas_paris.rename(columns={"gender":"sex"},inplace=True)

In [349]:
# atletas_olimpiadas.columns

In [350]:
# atletas_paris.columns

In [351]:
# atletas_paris_processed = atletas_paris.drop(columns=['code', 'current', 'name_short', 'name_tv',
#         'country_code', "country_long",
#        'nationality_long', 'nationality_code', 'height', 'weight',
#        'disciplines', 'events', 'birth_place', 'birth_country',
#        'residence_place', 'residence_country', 'nickname', 'hobbies',
#        'occupation', 'education', 'family', 'lang', 'coach', 'reason', 'hero',
#        'influence', 'philosophy', 'sporting_relatives', 'ritual',
#        'other_sports'])

In [352]:
# atletas_paris_processed.rename(columns={"gender":"sex"},inplace=True)

In [353]:
# atletas_paris_processed

In [354]:
atletas_total = pd.concat([atletas_olimpiadas,atletas_paris])

In [355]:
atletas_total

,athlete_id,name,sex,birth_date,birth_year,height,weight,country,country_noc,description,...,family,lang,coach,reason,hero,influence,philosophy,sporting_relatives,ritual,other_sports
0,2303707.0,A. Sansores,Male,NaN,NaN,NaN,NaN,Cuba,CUB,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2303703.0,Álvaro Ledón,Male,NaN,NaN,NaN,NaN,Cuba,CUB,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,921722.0,Abelardo Cuevas,Male,NaN,NaN,NaN,NaN,Cuba,CUB,"Abelardo Cuevas was a Cuban oboist, hornist, s...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2303702.0,V. Fernández,Male,NaN,NaN,NaN,NaN,Cuba,CUB,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2303738.0,A. F. Ruiz,Male,NaN,NaN,NaN,NaN,Cuba,CUB,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11108,NaN,ADA ETO Sefora,Female,2003-06-11,NaN,165.0,0.0,Equatorial Guinea,NaN,NaN,...,NaN,Spanish,Personal: Feliciano Javier y Mananses Mba Micha,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11109,NaN,LIUZZI Emanuela,Female,2000-04-27,NaN,0.0,0.0,Italy,NaN,NaN,...,NaN,Italian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11110,NaN,BOERS Isayah,Male,1999-06-19,NaN,NaN,NaN,Netherlands,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11111,NaN,STAUT Kevin,Male,1980-11-15,NaN,NaN,NaN,France,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11112,NaN,CARVELL Charlie,Male,2004-06-30,NaN,NaN,NaN,Great Britain,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [374]:
atletas_total.info()

<class 'pandas.DataFrame'>
Index: 166974 entries, 0 to 11112
Data columns (total 41 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   athlete_id          155861 non-null  float64
 1   name                166974 non-null  str
 2   sex                 166974 non-null  str
 3   birth_date          160324 non-null  str
 4   birth_year          151694 non-null  float64
 5   height              116222 non-null  float64
 6   weight              115259 non-null  float64
 7   country             166974 non-null  str
 8   country_noc         155861 non-null  str
 9   description         54863 non-null   str
 10  special_notes       60637 non-null   str
 11  code                11113 non-null   float64
 12  current             11113 non-null   object
 13  name_short          11110 non-null   str
 14  name_tv             11110 non-null   str
 15  function            11113 non-null   str
 16  country_code        11113 non-null   str
 17  country_long        11113 non-null   str
 18  nationality         11110 non-null   str
 19  nationality_long    11110 non-null   str
 20  nationality_code    11110 non-null   str
 21  disciplines         11113 non-null   str
 22  events              11113 non-null   str
 23  birth_place         8727 non-null    str
 24  birth_country       9475 non-null    str
 25  residence_place     6804 non-null    str
 26  residence_country   8288 non-null    str
 27  nickname            2966 non-null    str
 28  hobbies             4207 non-null    str
 29  occupation          9584 non-null    str
 30  education           5538 non-null    str
 31  family              5561 non-null    str
 32  lang                10605 non-null   str
 33  coach               8222 non-null    str
 34  reason              5846 non-null    str
 35  hero                3315 non-null    str
 36  influence           2155 non-null    str
 37  philosophy          2783 non-null    str
 38  sporting_relatives  2518 non-null    str
 39  ritual              857 non-null     str
 40  other_sports        1060 non-null    str
dtypes: float64(5), object(1), str(35)
memory usage: 53.5+ MB

### Metadados atletas

In [ ]:
metadatas_atletas_olympics_json = [
    {
        "arquivo": "athletes_gender_olympics.csv",
        "descricao": "Dados dos atletas nas respectivas edições dos Jogos Olímpicos",
        "formato": "csv",
        "delimitador": ",",
        "codificacao": "latin1",
        "quantidade_linhas": "166973",
        "dataset": "athletes info",
        "colunas": [
            {"name": "athlete_id", "tipo_dado": "float64", "descricao": "Identificador único do atleta"},
            {"name": "name", "tipo_dado": "string", "descricao": "Nome completo do atleta"},
            {"name": "sex", "tipo_dado": "string", "descricao": "Gênero do atleta"},
            {"name": "birth_date", "tipo_dado": "string", "descricao": "Data de nascimento do atleta"},
            {"name": "birth_year", "tipo_dado": "float64", "descricao": "Ano de nascimento do atleta"},
            {"name": "height", "tipo_dado": "float64", "descricao": "Altura do atleta em centímetros"},
            {"name": "weight", "tipo_dado": "float64", "descricao": "Peso do atleta em quilogramas"},
            {"name": "country", "tipo_dado": "string", "descricao": "País representado pelo atleta"},
            {"name": "country_noc", "tipo_dado": "string", "descricao": "Código do Comitê Olímpico Nacional"},
            {"name": "description", "tipo_dado": "string", "descricao": "Descrição geral ou biografia do atleta"},
            {"name": "special_notes", "tipo_dado": "string", "descricao": "Notas adicionais ou observações especiais sobre o atleta"},
            {"name": "code", "tipo_dado": "float64", "descricao": "Código interno ou do sistema relacionado ao atleta"},
            {"name": "current", "tipo_dado": "object", "descricao": "Indica se o atleta está atualmente ativo"},
            {"name": "name_short", "tipo_dado": "string", "descricao": "Versão abreviada do nome do atleta"},
            {"name": "name_tv", "tipo_dado": "string", "descricao": "Formato do nome utilizado para transmissão televisiva"},
            {"name": "function", "tipo_dado": "string", "descricao": "Função ou papel do atleta"},
            {"name": "country_code", "tipo_dado": "string", "descricao": "Código do país do atleta"},
            {"name": "country_long", "tipo_dado": "string", "descricao": "Nome completo do país"},
            {"name": "nationality", "tipo_dado": "string", "descricao": "Nacionalidade do atleta"},
            {"name": "nationality_long", "tipo_dado": "string", "descricao": "Descrição completa da nacionalidade do atleta"},
            {"name": "nationality_code", "tipo_dado": "string", "descricao": "Código que representa a nacionalidade do atleta"},
            {"name": "disciplines", "tipo_dado": "string", "descricao": "Modalidades esportivas em que o atleta compete"},
            {"name": "events", "tipo_dado": "string", "descricao": "Eventos em que o atleta participa"},
            {"name": "birth_place", "tipo_dado": "string", "descricao": "Local de nascimento do atleta"},
            {"name": "birth_country", "tipo_dado": "string", "descricao": "País de nascimento do atleta"},
            {"name": "residence_place", "tipo_dado": "string", "descricao": "Local onde o atleta reside atualmente"},
            {"name": "residence_country", "tipo_dado": "string", "descricao": "País onde o atleta reside atualmente"},
            {"name": "nickname", "tipo_dado": "string", "descricao": "Apelido do atleta"},
            {"name": "hobbies", "tipo_dado": "string", "descricao": "Hobbies e interesses do atleta"},
            {"name": "occupation", "tipo_dado": "string", "descricao": "Ocupação fora do esporte"},
            {"name": "education", "tipo_dado": "string", "descricao": "Formação educacional do atleta"},
            {"name": "family", "tipo_dado": "string", "descricao": "Informações familiares do atleta"},
            {"name": "lang", "tipo_dado": "string", "descricao": "Idiomas falados pelo atleta"},
            {"name": "coach", "tipo_dado": "string", "descricao": "Treinador do atleta"},
            {"name": "reason", "tipo_dado": "string", "descricao": "Motivação ou razão para praticar o esporte"},
            {"name": "hero", "tipo_dado": "string", "descricao": "Herói ou inspiração esportiva do atleta"},
            {"name": "influence", "tipo_dado": "string", "descricao": "Pessoas que influenciaram o atleta"},
            {"name": "philosophy", "tipo_dado": "string", "descricao": "Filosofia ou mentalidade pessoal do atleta"},
            {"name": "sporting_relatives", "tipo_dado": "string", "descricao": "Parentes envolvidos no esporte"},
            {"name": "ritual", "tipo_dado": "string", "descricao": "Rituais pessoais ou pré-competição"},
            {"name": "other_sports", "tipo_dado": "string", "descricao": "Outros esportes praticados pelo atleta"}
        ]
    }
]

In [377]:
caminho_metadata_athletes = caminho_metadata_bronze / "athletes_gender_olympics.json"
criacao_metadados(caminho_metadata_athletes,metadatas_atletas_olympics_json)

In [356]:
path = "./bronze/athletes_gender_olympics.csv"
if os.path.exists(path):
    pass
else:
    atletas_total.to_csv(path)

### Modalidades

In [357]:
modalidades_paris = pd.read_csv("./raw/events/events_paris.csv")
modalidades_olimpicas = pd.read_csv("./raw/results/olympics_results.csv")

In [358]:
modalidades_olimpicas

,result_id,event_title,edition,edition_id,sport,result_date,result_location,result_participants,result_format,result_detail,result_description
0,40000,"Individual, Men",1900 Summer Olympics,2,Golf,2 October 1900,"Golf de Compiègne, Compiègne",12 from 3 countries,36 holes stroke play,na,"Charles Sands, of the St. Andrews Golf Club in..."
1,925229,"Individual, Handicap, Men",1900 Summer Olympics,2,Golf,3 October 1900,"Golf de Compiègne, Compiègne",19 from 4 countries,18 holes stroke play with handicaps.,na,"Al Lambert won the handicap event, playing off..."
2,40001,"Individual, Women",1900 Summer Olympics,2,Golf,3 October 1900,"Golf de Compiègne, Compiègne",10 from 3 countries,9 holes stroke play,na,The ladies’ event took place the day after the...
3,925231,"Individual, Professional, Men",1900 Summer Olympics,2,Golf,3 October 1900,"Golf de Compiègne, Compiègne",2 from 1 countries,36 holes stroke play.,na,Chevalier and Phillips were local professional...
4,926022,Individual (Second Flight Consolation Champion...,1904 Summer Olympics,3,Golf,22 – 25 September 1904,"Glen Echo Country Club, Normandy",16 from 1 countries,Single-elimination tournament.,na,na
...,...,...,...,...,...,...,...,...,...,...,...
7389,9001206,"1,500 metres, Women",2018 Winter Olympics,60,Short Track Speed Skating,17 February 2018,"Gangneung Ice Arena, Gangneung Olympic Park, C...",36 from 17 countries,Placements 1-12 based on final and B final. D...,na,na
7390,9001157,"5,000 metres Relay, Men",2018 Winter Olympics,60,Short Track Speed Skating,13 – 22 February 2018,"Gangneung Ice Arena, Gangneung Olympic Park, C...",34 from 8 countries,Placements 1-8 based on final and B final.,na,na
7391,9001142,"1,500 metres, Men",2018 Winter Olympics,60,Short Track Speed Skating,10 February 2018,"Gangneung Ice Arena, Gangneung Olympic Park, C...",37 from 18 countries,Placements 1-12 based on final and B final. D...,na,na
7392,9001121,"1,000 metres, Men",2018 Winter Olympics,60,Short Track Speed Skating,13 – 17 February 2018,"Gangneung Ice Arena, Gangneung Olympic Park, C...",32 from 14 countries,Placements 1-8 based on final and B final. De...,na,na
7393,9001221,"3,000 metres Relay, Women",2018 Winter Olympics,60,Short Track Speed Skating,10 – 20 February 2018,"Gangneung Ice Arena, Gangneung Olympic Park, C...",37 from 8 countries,Placements 1-8 based on final and B final.,na,na

In [359]:
modalidades_paris

,event,tag,sport,sport_code,sport_url
0,Men's Individual,archery,Archery,ARC,https://olympics.com/en/paris-2024/sports/archery
1,Women's Individual,archery,Archery,ARC,https://olympics.com/en/paris-2024/sports/archery
2,Men's Team,archery,Archery,ARC,https://olympics.com/en/paris-2024/sports/archery
3,Women's Team,archery,Archery,ARC,https://olympics.com/en/paris-2024/sports/archery
4,Mixed Team,archery,Archery,ARC,https://olympics.com/en/paris-2024/sports/archery
...,...,...,...,...,...
324,Men's Freestyle 65kg,wrestling,Wrestling,WRE,https://olympics.com/en/paris-2024/sports/wres...
325,Men's Freestyle 74kg,wrestling,Wrestling,WRE,https://olympics.com/en/paris-2024/sports/wres...
326,Men's Freestyle 86kg,wrestling,Wrestling,WRE,https://olympics.com/en/paris-2024/sports/wres...
327,Men's Freestyle 97kg,wrestling,Wrestling,WRE,https://olympics.com/en/paris-2024/sports/wres...
328,Men's Freestyle 125kg,wrestling,Wrestling,WRE,https://olympics.com/en/paris-2024/sports/wres...

In [360]:
overall_modalidades = pd.concat([modalidades_olimpicas,modalidades_paris])

In [361]:
overall_modalidades

,result_id,event_title,edition,edition_id,sport,result_date,result_location,result_participants,result_format,result_detail,result_description,event,tag,sport_code,sport_url
0,40000.0,"Individual, Men",1900 Summer Olympics,2.0,Golf,2 October 1900,"Golf de Compiègne, Compiègne",12 from 3 countries,36 holes stroke play,na,"Charles Sands, of the St. Andrews Golf Club in...",NaN,NaN,NaN,NaN
1,925229.0,"Individual, Handicap, Men",1900 Summer Olympics,2.0,Golf,3 October 1900,"Golf de Compiègne, Compiègne",19 from 4 countries,18 holes stroke play with handicaps.,na,"Al Lambert won the handicap event, playing off...",NaN,NaN,NaN,NaN
2,40001.0,"Individual, Women",1900 Summer Olympics,2.0,Golf,3 October 1900,"Golf de Compiègne, Compiègne",10 from 3 countries,9 holes stroke play,na,The ladies’ event took place the day after the...,NaN,NaN,NaN,NaN
3,925231.0,"Individual, Professional, Men",1900 Summer Olympics,2.0,Golf,3 October 1900,"Golf de Compiègne, Compiègne",2 from 1 countries,36 holes stroke play.,na,Chevalier and Phillips were local professional...,NaN,NaN,NaN,NaN
4,926022.0,Individual (Second Flight Consolation Champion...,1904 Summer Olympics,3.0,Golf,22 – 25 September 1904,"Glen Echo Country Club, Normandy",16 from 1 countries,Single-elimination tournament.,na,na,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,NaN,NaN,NaN,NaN,Wrestling,NaN,NaN,NaN,NaN,NaN,NaN,Men's Freestyle 65kg,wrestling,WRE,https://olympics.com/en/paris-2024/sports/wres...
325,NaN,NaN,NaN,NaN,Wrestling,NaN,NaN,NaN,NaN,NaN,NaN,Men's Freestyle 74kg,wrestling,WRE,https://olympics.com/en/paris-2024/sports/wres...
326,NaN,NaN,NaN,NaN,Wrestling,NaN,NaN,NaN,NaN,NaN,NaN,Men's Freestyle 86kg,wrestling,WRE,https://olympics.com/en/paris-2024/sports/wres...
327,NaN,NaN,NaN,NaN,Wrestling,NaN,NaN,NaN,NaN,NaN,NaN,Men's Freestyle 97kg,wrestling,WRE,https://olympics.com/en/paris-2024/sports/wres...
328,NaN,NaN,NaN,NaN,Wrestling,NaN,NaN,NaN,NaN,NaN,NaN,Men's Freestyle 125kg,wrestling,WRE,https://olympics.com/en/paris-2024/sports/wres...

In [378]:
overall_modalidades.info()

<class 'pandas.DataFrame'>
Index: 7723 entries, 0 to 328
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   result_id            7394 non-null   float64
 1   event_title          7394 non-null   str
 2   edition              7394 non-null   str
 3   edition_id           7394 non-null   float64
 4   sport                7723 non-null   str
 5   result_date          7394 non-null   str
 6   result_location      7393 non-null   str
 7   result_participants  7394 non-null   str
 8   result_format        7394 non-null   str
 9   result_detail        7394 non-null   str
 10  result_description   7394 non-null   str
 11  event                329 non-null    str
 12  tag                  329 non-null    str
 13  sport_code           329 non-null    str
 14  sport_url            329 non-null    str
dtypes: float64(2), str(13)
memory usage: 965.4 KB

In [380]:
metadata_modalidades_olympics_json = [
    {
        "arquivo": "modalidades_olympics.csv",
        "descricao": "Dados das modalidades dispostas nos Jogos Olímpicos",
        "formato": "csv",
        "delimitador": ",",
        "codificacao": "latin1",
        "quantidade_linhas": "166973",
        "dataset": "modalidades_olimpiadas",
        "colunas": [
            {"name": "result_id", "tipo_dado": "float64", "descricao": "Identificador único do resultado"},
            {"name": "event_title", "tipo_dado": "string", "descricao": "Título do evento esportivo"},
            {"name": "edition", "tipo_dado": "string", "descricao": "Nome da edição dos Jogos Olímpicos"},
            {"name": "edition_id", "tipo_dado": "float64", "descricao": "Identificador único da edição dos Jogos Olímpicos"},
            {"name": "sport", "tipo_dado": "string", "descricao": "Modalidade esportiva"},
            {"name": "result_date", "tipo_dado": "string", "descricao": "Data em que o resultado ocorreu"},
            {"name": "result_location", "tipo_dado": "string", "descricao": "Local onde o evento foi realizado"},
            {"name": "result_participants", "tipo_dado": "string", "descricao": "Participantes envolvidos no evento"},
            {"name": "result_format", "tipo_dado": "string", "descricao": "Formato da competição ou disputa"},
            {"name": "result_detail", "tipo_dado": "string", "descricao": "Detalhes adicionais sobre o resultado"},
            {"name": "result_description", "tipo_dado": "string", "descricao": "Descrição completa do resultado do evento"},
            {"name": "event", "tipo_dado": "string", "descricao": "Nome específico do evento"},
            {"name": "tag", "tipo_dado": "string", "descricao": "Etiqueta ou categoria associada ao evento"},
            {"name": "sport_code", "tipo_dado": "string", "descricao": "Código identificador da modalidade esportiva"},
            {"name": "sport_url", "tipo_dado": "string", "descricao": "URL com informações adicionais sobre a modalidade"}
        ]
    }
]

In [381]:
caminho_metadata_modalidade = caminho_metadata_bronze / "modalidades_olympics.json"
criacao_metadados(caminho_metadata_modalidade,metadata_modalidades_olympics_json)

In [362]:
path = "./bronze/modalidades_olympics.csv"
if os.path.exists(path):
    pass
else:
    overall_modalidades.to_csv(path)